services:
  tnderlike:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - '12021:80'
    volumes:
      - ./logs:/var/log/tnderlike/
    depends_on:
      - tnderlike-db

  tnderlike-db:
    build:
      context: .
      dockerfile: docker/db/dev.Dockerfile
    ports:
    - "10001:5432"
    env_file:
      - docker/db/db.env
    volumes:
      - ./docker/db/migration/:/docker-entrypoint-initdb.d
      - tnderlikedb:/var/lib/postgresql/data/

volumes:
  tnderlikedb:
