name: tnderlike
server:
  logs:
    info: /var/log/tnderlike/tnderlike.info.log
    error: /var/log/tnderlike/tnderlike.error.log
  port: "80"
  timeout: 10 # seconds
  limiter:
    rate: 20
    burst: 100
    expiration: 3 # minutes
  origin:
    - "*"
