// Code generated by mockery v2.43.2. DO NOT EDIT.

package paseto

import mock "github.com/stretchr/testify/mock"

// MockHandlerPaseto is an autogenerated mock type for the Handler type
type MockHandlerPaseto struct {
	mock.Mock
}

// Extract provides a mock function with given fields: _a0
func (_m *MockHandlerPaseto) Extract(_a0 string) (Payload, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (Payload, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) Payload); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(Payload)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Generate provides a mock function with given fields: _a0
func (_m *MockHandlerPaseto) Generate(_a0 Payload) (string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(Payload) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(Payload) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(Payload) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockHandlerPaseto creates a new instance of MockHandlerPaseto. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandlerPaseto(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandlerPaseto {
	mock := &MockHandlerPaseto{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
